### ISSUE TITLE
[QC] Test deployability of certmanager

### ISSUE THREAD

**Issue by r-casula** [Aridhia-Open-Source/PHEMS_federated_node#109]
Endpoints to be tested: N/A non-API change.

Version to deploy: `0.10.0-3e189a`

---
Acceptance Criteria:
The `certmanager` has been deployed. Can be double checked with the `cmctl` CLI tool. See [docs](https://aridhia.atlassian.net/wiki/spaces/DEV/pages/3340304402/cmctl+-+The+CLI+Tool+for+cert-manager). 

Then run 
```sh
cmctl status certificate -n qcfederatednode www
```
And you should see some info about the SSL.
---
QC notes:
Edit the values files to include:
```yaml
cert-manager:
  namespace: fn-certmanager
  enabled: true
certs:
  azure:
    configmap: azuredns-config
    secretName: azuredns-config
```
