### ISSUE TITLE
[QC] Install the task controller as subchart

### ISSUE THREAD

**Issue by r-casula** [Aridhia-Open-Source/PHEMS_federated_node#138]
Endpoints to be tested:
No endpoints, mostly upgrade process.

Before updating, add the following to a file, called `values.yaml`
```yaml
outboundMode: true
fn-task-controller:
    idp:
        github:
            secret_name: github-app
            secret_key: GH_SECRET
            clientid_key: GH_CLIENT_ID
            orgAndRepo: Aridhia-Open-Source/Federated-Node-Example-App
    delivery:
        other:
            url: federation-test.uksouth.tre.aridhia.io
            auth_type: AzCopy
    storage:
        size: 1Gi
        azure:
            secretName: fnazstorage
            shareName: files
global:
    host: qc-federatednode.qc.aridhiatest.net
    namespaces:
        keycloak: identities
        tasks: analytics
        controller: fn-controller
```
Run the upgrade with
```sh
NAMESPACE=$(helm list -A -o json | jq -r '.[] | select(.name=="federatednode") | .namespace')

helm upgrade federatednode federated-node/federated-node -n $NAMESPACE --reuse-values -f values.yaml --version=0.12.0-v738103
```

Once is successful you can "copy" 2 existing secrets to the `fn-controller` namespace:
```sh
kubectl get secret aridhia-open-source-federated-node-example-app -n "$NAMESPACE" -o yaml | sed '/namespace\|creationTimestamp\|resourceVersion\|uid:/d;' | kubectl apply -n fn-controller -f -

kubectl get secret dre-delivery -n "$NAMESPACE" -o yaml | sed '/namespace\|creationTimestamp\|resourceVersion\|uid:/d;' | kubectl apply -n fn-controller -f -
```
---
Acceptance Criteria:
- upgrade is successful
- (optional) after upgrade the following can be pasted into a file (`task.yaml`), and applied to the cluster with `kubectl apply -f task.yaml`:
    ```yaml
    apiVersion: tasks.federatednode.com/v1
    kind: Analytics
    metadata:
        name: test-task-1
    spec:
        image: aridhia-open-source/rtest:3.0-dev
        db_query:
            query: "SELECT * FROM carspeed"
            dialect: postgres
        project: project12
        source:
            repository: Aridhia-Open-Source/Federated-Node-Example-App
        user:
            idpId: '100773423'
            username: r-casula
    ```
  This should trigger a cascade effect that will end up in a task to be created, and results being delivered to the shared dev DRE `federation-node` workspace inbox
---
QC notes:
- You can use any DRE hub like QC, just replace the `delivery.other.url` with the hostname of the workspace in the values at deployment time. Then create a new secret after the upgrade is successful, following [these steps](https://github.com/Aridhia-Open-Source/federated-node-task-controller/wiki/Automatic-results-delivery#other-delivery).
Chart version: `0.12.0-v738103`
